
version: 2

sources:
  - name: bigquery_source
    schema: Staging

    tables:
      - name: orders

models:
    - name: transformed_orders
      description: "Orders transformed table"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
      config:
        materialized: table
        alias: orders_rpt